### PR TITLE
Improve module usability as dependency in Angular.JS projects.

### PR DESCRIPTION
**Pull request by larixer**
Protect module with IIFE to prevent variable collisions. Add required sections into bower.json.

### CODE REVIEW

**Comment by nullivex** [comment]
Can you please get the tests passing?

**Comment by vlasenko** [comment]
I have checked and see that currently tests aren't passing on main repository source code. So this is not the problem with the pull request itself. It's the problem that karma configuration is outdated.

**Comment by vlasenko** [comment]
Close to trigger CI rebuild

**Comment by vlasenko** [comment]
Prerequisites for running karma tests has been updated

**Comment by nullivex** [comment]
Did you bump the version and write a changelog? If not can you please do so.

I would consider a minor bump

0.3.0

Thanks

**Pull request merged**
